{
 "title": "reports",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "startDate", "label": "Start Date" },
   { "name": "endDate", "label": "End Date" }
  ]
 },
 "panels": [
  {
   "title": "Productos con mayor cantidad de entradas",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"REPORTS\")\n  |> range(start: time(v: \"${startDate}\"), stop: time(v: \"${endDate}\"))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ProductInput\")\n  |> group(columns: [\"Code\",\"SubsidiaryId\"])\n  |> aggregateWindow(every: 1y, fn: sum, createEmpty: false)\n  |> yield(name: \"sum\")"
    }
   ]
  },
  {
   "title": "Productos con mayor cantidad de salidas",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: \"REPORTS\")\n  |> range(start: time(v: \"${startDate}\"), stop: time(v: \"${endDate}\"))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ProductOutput\")\n  |> group(columns: [\"Code\",\"SubsidiaryId\"])\n  |> aggregateWindow(every: 1y, fn: sum, createEmpty: false)\n  |> yield(name: \"sum\")"
    }
   ]
  },
  {
   "title": "Evolución de entradas en el tiempo",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "query": "from(bucket: \"REPORTS\")\n  |> range(start: time(v: \"${startDate}\"), stop: time(v: \"${endDate}\"))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ProductInput\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Quantity\")\n  |> group(columns: [\"Code\"])\n  |> aggregateWindow(every: 24h, fn: sum, createEmpty: false)\n  |> yield(name: \"sum\")"
    }
   ]
  },
  {
   "title": "Evolución de salidas en el tiempo",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "query": "from(bucket: \"REPORTS\")\n  |> range(start: time(v: \"${startDate}\"), stop: time(v: \"${endDate}\"))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ProductOutput\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Quantity\")\n  |> group(columns: [\"Code\"])\n  |> aggregateWindow(every: 24h, fn: sum, createEmpty: false)\n  |> yield(name: \"sum\")"
    }
   ]
  },
  {
   "title": "Entradas/Salidas",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {
     "query": "from(bucket: \"REPORTS\")\n  |> range(start: time(v: \"${startDate}\"), stop: time(v: \"${endDate}\"))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ProductOutput\" or r[\"_measurement\"] == \"ProductInput\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Quantity\")\n  |> drop(columns: [\"SubsidiaryUbication\",\"UserName\",\"UserPhoneNumber\",\"UserRol\",\"CompanyId\"])\n  |> aggregateWindow(every: 24h, fn: sum, createEmpty: false)\n  |> yield(name: \"sum\")"
    }
   ]
  },
  {
   "title": "Entradas/Salidas",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {
     "query": "from(bucket: \"REPORTS\")\n  |> range(start: time(v: \"${startDate}\"), stop: time(v: \"${endDate}\"))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ProductOutput\" or r[\"_measurement\"] == \"ProductInput\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Quantity\")\n  |> drop(columns: [\"SubsidiaryUbication\",\"UserName\",\"UserPhoneNumber\",\"UserRol\",\"CompanyId\"])\n  |> aggregateWindow(every: 24h, fn: sum, createEmpty: false)\n  |> yield(name: \"sum\")"
    }
   ]
  },
  {
   "title": "Beneficio/Pérdida de productos",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 81 },
   "targets": [
    {
     "query": "from(bucket: \"REPORTS\")\n  |> range(start: time(v: \"${startDate}\"), stop: time(v: \"${endDate}\"))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ProductInput\")\n  |> filter(fn: (r) => r[\"_field\"] == \"IncomePrice\")\n  |> aggregateWindow(every: 24h, fn: sum, createEmpty: false)\n  |> yield(name: \"last\")\n  |> map(fn: (r) => ({ r with _value: r._value * -1.0}))\n \n"
    },
    {
     "query": " from(bucket: \"REPORTS\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ProductOutput\")\n  |> filter(fn: (r) => r[\"_field\"] == \"SellingPrice\")\n  |> aggregateWindow(every: 24h, fn: sum, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Tabla entrada de productos",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 93 },
   "targets": [
    {
     "query": "from(bucket: \"REPORTS\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ProductInput\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Quantity\")\n  |> drop(columns: [\"CompanyId\", \"SubsidiaryUbication\"])\n  |> group(columns: [\"Code\",\"UserEmail\"], mode:\"by\")  \n  |> aggregateWindow(every: 24h, fn: sum, createEmpty: false)\n  |> yield(name: \"sum\")"
    }
   ]
  },
  {
   "title": "Tabla salida de productos",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 105 },
   "targets": [
    {
     "query": "from(bucket: \"REPORTS\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ProductOutput\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Quantity\")\n  |> drop(columns: [\"CompanyId\", \"SubsidiaryUbication\"])\n  |> group(columns: [\"Code\",\"UserEmail\"], mode:\"by\")  \n  |> aggregateWindow(every: 24h, fn: sum, createEmpty: false)\n  |> yield(name: \"sum\")"
    }
   ]
  },
  {
   "title": "Tabla beneficio de productos",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 117 },
   "targets": [
    {
     "query": "from(bucket: \"REPORTS\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ProductOutput\")\n  |> filter(fn: (r) => r[\"_field\"] == \"SellingPrice\")\n  |> drop(columns: [\"CompanyId\", \"SubsidiaryUbication\"])\n  |> group(columns: [\"Code\",\"UserEmail\"], mode:\"by\")  \n  |> aggregateWindow(every: 24h, fn: sum, createEmpty: false)\n  |> yield(name: \"sum\")"
    }
   ]
  },
  {
   "title": "Tabla pérdida de productos",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 129 },
   "targets": [
    {
     "query": "from(bucket: \"REPORTS\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ProductInput\")\n  |> filter(fn: (r) => r[\"_field\"] == \"IncomePrice\")\n  |> drop(columns: [\"CompanyId\", \"SubsidiaryUbication\"])\n  |> group(columns: [\"Code\",\"UserEmail\"], mode:\"by\")  \n  |> aggregateWindow(every: 24h, fn: sum, createEmpty: false)\n  |> yield(name: \"sum\")"
    }
   ]
  }
 ]
}