CREATE DATABASE IF NOT EXISTS dbaderezosdev;
       
USE dbaderezosdev;

-- USER
CREATE TABLE IF NOT EXISTS User(
    Id      VARCHAR(36) PRIMARY KEY NOT NULL,
    Name    VARCHAR(80),
    Rol     VARCHAR(80),
    Email   VARCHAR(80),
    PhoneNumber   VARCHAR(80),
    BirthDate     DATE    
);

-- TOKEN SESSIONS
CREATE TABLE IF NOT EXISTS SessionToken(
    Token   VARCHAR(2000),
    Time    DATETIME,
    UserId  VARCHAR(36)
);

CREATE EVENT IF NOT EXISTS Delete_Tokens_Event
    ON SCHEDULE
        EVERY 10 MINUTE
ON COMPLETION PRESERVE
DO
    DELETE FROM  SessionToken WHERE Time < DATE_SUB(NOW(), INTERVAL 30 MINUTE);



-- TRUNCATE ALL TABLES
DELIMITER //
CREATE PROCEDURE TruncateAllTables()
BEGIN
    SET FOREIGN_KEY_CHECKS = 0;
    TRUNCATE TABLE User;
    TRUNCATE TABLE SessionToken;
    SET FOREIGN_KEY_CHECKS = 1;
END //
DELIMITER ;

